### ISSUE TITLE
Jumbled Output in Firefox

### ISSUE THREAD

**Issue by JustOneMoreDog** [honze-net/nmap-bootstrap-xsl#6]
when running the command `nmap -sS -T4 -A -sC -oA scanme --stylesheet /root/nmap-bootstrap-xsl/nmap-bootstrap.xsl` , and then opening the file xml file in firefox I get, 

```
cpe:/a:openbsd:openssh:7.2p2cpe:/o:linux:linux_kernel
c4f8ade8f80477decf150d630a187e49
2048.0
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQD8ArTOHWzqhwcyAZWc2CmxfLmVVTwfLZf0zhCBREGCpS2WC3NhAKQ2zefCHCU8XTC8hY9ta5ocU+p7S52OGHlaG7HuA5Xlnihl1INNsMX7gpNcfQEYnyby+hjHWPLo4++fAyO/lB8NammyA13MzvJy8pxvB9gmCJhVPaFzG5yX6Ly8OIsvVDk+qVa5eLCIua1E7WGACUlmkEGljDvzOaBdogMQZ8TGBTqNZbShnFH1WsUxBtJNRtYfeeGjztKTQqqj4WD5atU8dqV/iwmTylpE7wdHZ+38ckuYL9dmUPLh4Li2ZgdY6XniVOBGthY5a2uJ2OFp2xe1WS9KvbYjJ/tH


228fb197bf0f1708fc7e2c8fe9773a48
256
ecdsa-sha2-nistp256
AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPiFJd2F35NPKIQxKMHrgPzVzoNHOJtTtM+zlwVfxzvcXPFFuQrOL7X6Mi9YQF9QRVJpwtmV9KAtWltmk3qm4oc=


e6ac27a3b5a9f1123c34a55d5beb3de9
256
ssh-ed25519
AAAAC3NzaC1lZDI1NTE5AAAAIC/RjKhT/2YPlCgFQLx+gOXhC6W3A3raTzjlXQMT8Msk


cpe:/a:apache:http_server:2.4.18Apache/2.4.18 (Ubuntu)






cpe:/o:linux:linux_kernel:3.12


cpe:/o:linux:linux_kernel:3.13


cpe:/o:linux:linux_kernel:3
cpe:/o:linux:linux_kernel:4


cpe:/o:linux:linux_kernel:3


cpe:/o:linux:linux_kernel:4.8


cpe:/o:linux:linux_kernel:4.4


cpe:/o:linux:linux_kernel:3.16


cpe:/o:linux:linux_kernel:3.18


cpe:/o:linux:linux_kernel:4.2


cpe:/h:asus:rt-n56u
cpe:/o:linux:linux_kernel:3.4
```

When I try and run the original command ( ` nmap -sS -T4 -A -sC -oA scanme --stylesheet https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl 10.10.10.75`) given in the readme I get an error 

```
Error loading stylesheet: An unknown error has occurred (805303f4)https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl
```

Do you know what I am doing wrong?

**Comment by honze-net** [comment]
When viewing the XML, does the machine have an internet connection? Connecting the machine should resolve this issue.

If not: Please attach your scanme.xml

**Comment by JustOneMoreDog** [comment]
It has an internet connection.  I even tried using your style sheet locally too.  Here is the scanme.xml .  Thank you for looking into this :)



[scanme.zip](https://github.com/honze-net/nmap-bootstrap-xsl/files/3487426/scanme.zip)

**Comment by honze-net** [comment]
The scanme.xml looks perfectly fine. What version of Firefox do you use? Do you use any AdBlocker or similar? How do you open the XML file in Firefox?

**Comment by JustOneMoreDog** [comment]
Its a default install of Firefox Quantum 68.0.1 (64-bit).  If the XML is good then let me try some other browsers real fast and see if that was the issue.  It seems to be doing it on chrome as well.

**Comment by JustOneMoreDog** [comment]
Interesting.  After doing some more googling I decided to try and load the file into my browser as an actual website than a file and it worked.  If I do `http://10.0.33.69:9090/scanme.xml` (while running python -m SimpleHTTPServer 9090) I can get this to load just fine.  However, if I do `file:///C:/Users/sandwich/Desktop/scanme.xml` it will give me the `Error loading stylesheet: An unknown error has occurred (805303f4)https://raw.githubusercontent.com/honze-net/nmap-bootstrap-xsl/master/nmap-bootstrap.xsl` error.  

Even more interesting, once I load it using the python webserver, it then will work using just the file extension.  Maybe it is just getting cached?

**Comment by honze-net** [comment]
Oh, I suspect that it has something to do with this change in Firefox 68: [https://support.mozilla.org/bm/questions/1264318](https://support.mozilla.org/bm/questions/1264318)
Could you open the web console in Firefox and look for any errors?
At least you have one way to view the XML, which is not very satisfying, but it works. Maybe you can get away with the cached version. I wonder how long this will last.

Maybe a complete offline version of the XSL could fix this issue. I hope there is an automated way to pull every include into the XSL.

**Comment by JustOneMoreDog** [comment]
I will update you hopefully today if not tomorrow.  Have to finish some deadlines first :)

**Comment by JustOneMoreDog** [comment]
I can confirm the console did not output any errors

**Comment by honze-net** [comment]
I failed to reproduce the bug under Windows 10 and Firefox 68.0.1 (64-Bit). It works as intended. I really want to help, but I am afraid, that I have no solution at the moment.

**Comment by JustOneMoreDog** [comment]
im perfectly fine just doing the work around so its no big deal if we cant fix it.  At the very least, if someone else has the problem they will have a way to get around it.  I appreciate your time and patience on this :)

**Comment by honze-net** [comment]
Thank you very much for reporting it in the first place and taking your time to investigate the issue.

**Comment by KazDev17** [comment]
for anyone in 2024 having same problem, i'd suggest using the exiftool (apt-get install exiftool) to convert the .xml to .html so it can be interpreted by firefox

xsltproc scanme.xml > scanme.html

documentation : https://github.com/exiftool/exiftool
