### ISSUE TITLE
how can i scan with subdomain list?

### ISSUE THREAD

**Issue by Phoenix1112** [honze-net/nmap-bootstrap-xsl#7]
hello. thanks for this project. How can i scan ports with subdomain list ? can you add a new feature for it?

**Comment by honze-net** [comment]
Hello, I am glad you like it! Thank you!

Can you explain what your exact problem is, please.

**Comment by Phoenix1112** [comment]
in this way, we need to enter the domain names to be manually searched.but imagine that we have a subdomain.txt file with thousands of subdomain names. the program should open subdomain.txt files and scan all subdomains at once. this feature would be nice if added.

**Comment by honze-net** [comment]
I think you should look into the nmap option `-iL`. That should resolve the issue for you.
[Target Specification | Nmap Network Scanning](https://nmap.org/book/man-target-specification.html)

**Comment by Phoenix1112** [comment]
Tomorrow i will try .. i will answer tomorrow about this

**Comment by honze-net** [comment]
Do you have any questions or can I close this issue?
